### ISSUE TITLE
Socket connection keeps reconnecting

### ISSUE THREAD

**Issue by mregni** [pluja/whishper#10]
Hi,

I was testing out Whishper and it looks very promissing!

After setting up the docker-compose file with the correct path and the chown command the containers all start but then I can't seem to do anything.
The UI itelf loads but can't connect over the websocket connection. Also the /languages call fails with a status 500.

![image](https://github.com/pluja/whishper/assets/22617019/ef79b411-5d0d-44d2-bb02-4f5ccb278eb0)

I had a look in the container logs and in the backend container I find these errors:
```
06:06:58 DBG database/mongo.go:127 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:06:58 DBG monitor/monitor.go:25 > Pending transcriptions: 0
06:07:13 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:07:28 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:07:43 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:07:58 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:08:13 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:08:28 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
06:08:43 DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
```

And in the web container logs:
````
Listening on 0.0.0.0:3000
/api/transcriptions
TypeError: fetch failed
    at fetch (file:///app/shims.js:20346:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///app/server/index.js:3998:14)
    at async respond (file:///app/server/index.js:3823:22)
    at async fetch (file:///app/server/index.js:3633:26)
    at async Object.fetch (file:///app/server/index.js:3573:12)
    at async file:///app/server/index.js:1996:20
    at async load (file:///app/server/chunks/0-9ff9db82.js:9:20)
    at async load_data (file:///app/server/index.js:1978:18)
    at async file:///app/server/index.js:3307:18 {
  cause: [Error: 98FB36B0C17F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
/api/transcriptions
SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///app/server/index.js:2064:25)
    at async load (file:///app/server/chunks/0-9ff9db82.js:10:14)
    at async load_data (file:///app/server/index.js:1978:18)
    at async respond_with_error (file:///app/server/index.js:2938:20)
    at async resolve (file:///app/server/index.js:3985:16)
    at async respond (file:///app/server/index.js:3823:22)
    at async Array.ssr (file:///app/handler.js:1221:3)
/api/transcriptions
```

I think it's because I set a root username and password for the mongo db but never specify the credentials in the backend container. Are there some env vars I missed?

Here is my docker-compose file for reference (I removed ngigx since I'm will implement traefik later and I changed the directories as well)
```
version: "3.9"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: whishper-db
    volumes:
      - /cat/docker/volumes/ai_whishper/data/db:/data/db
      - /cat/docker/volumes/ai_whishper/data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - /cat/docker/volumes/ai_whishper/libretranslate/data:/home/libretranslate/.local/share
      - /cat/docker/volumes/ai_whishper/libretranslate/cache:/home/libretranslate/.local/cache
    environment:
      - LT_LOAD_ONLY=en,nl
      - LT_DISABLE_WEB_UI=True
      - LT_UPDATE_MODELS=True
      - LT_THREADS=8
    tty: true
    expose:
      - 5000
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 15s
      timeout: 10s
      start_period: 5s
      retries: 5

  transcription-api:
    container_name: whisper-api
    image: pluja/whishper-transcription-api:latest
    restart: unless-stopped
    volumes:
      - /cat/docker/volumes/ai_whishper/app/whisper_models:/app/models
      - /cat/docker/volumes/ai_whishper/app/uploads:/app/uploads
    environment:
      - WHISPER_MODELS_DIR=/app/models
      - UPLOAD_DIR=/app/uploads
      - WHISPER_MODELS=tiny,small
      - WHISHPER_HOST=whishper-backend:8080
    expose:
      - 8000

  whishper-backend:
    container_name: whishper-backend
    image: pluja/whishper-backend:latest
    restart: unless-stopped
    volumes:
      - /cat/docker/volumes/ai_whishper/app/uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
      translate:
        condition: service_healthy
      transcription-api:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/api/transcriptions || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
    expose:
      - 8080

  whishper-frontend:
    container_name: whishper-web
    image: pluja/whishper-frontend:latest
    restart: unless-stopped
    environment:
      - PUBLIC_INTERNAL_API_HOST=http://192.168.72.28:5487
      - PUBLIC_TRANSLATION_API_HOST=
      - PUBLIC_API_HOST=-
    depends_on:
      transcription-api:
        condition: service_healthy
    ports:
      - 5487:3000

```

Let me know if you need some info to help me out and thanks in advance!

**Comment by pluja** [comment]
Yes, it most probably is due to the MongoDB credentials. I will add optional env variables for that. For the time being, you should delete the created database files in `whishper_data` folder and restart, leaving the default password...

**Comment by mregni** [comment]
Thanks for the fast reply!

I removed my stack and volumes and recreated the docker compose. Now I don't have a database error any more when I use the default username/password. But the frontend container still had this error:
```
SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///app/server/index.js:2064:25)
    at async load (file:///app/server/chunks/0-9ff9db82.js:10:14)
    at async load_data (file:///app/server/index.js:1978:18)
    at async respond_with_error (file:///app/server/index.js:2938:20)
    at async resolve (file:///app/server/index.js:3985:16)
    at async respond (file:///app/server/index.js:3823:22)
    at async Array.ssr (file:///app/handler.js:1221:3)
/api/transcriptions
```

Also, the socket call and the /languages call are still failing. not sure why.  Backend logs seem to be fine 
![image](https://github.com/pluja/whishper/assets/22617019/83d7364a-9da3-44ee-b1f0-b527d706bb35)

**Comment by pluja** [comment]
The issue is because you removed the `nginx` container, which is the one that coordinates the frontend requests to each of the containers. Is there any particular reason for that? Connecting to the front-end container will not work, the frontend won't coordinate the proxies to each container, see the `nginx.conf` to see what nginx is doing: https://github.com/pluja/whishper/blob/main/nginx.conf

**Comment by mregni** [comment]
Hmmm, well I'm using Traefik for my reverse proxy. I added the nginx and it started working. Sorry for the nooby mistake!
Going to test the tool some more, are you open for feature request or pull requests?

Thanks for the support btw!

**Comment by pluja** [comment]
Of course, feel free to create pull requests and feature requests. I will address them when I have time!
