### ISSUE TITLE
File upload returns HTTP status 413 / 500 / 502

### ISSUE THREAD

**Issue by North-West-Wind** [pluja/whishper#13]
When uploading a file, a POST request is made that fails with HTTP status 500 / 502. The interface shows "Success", but nothing actually changed.

Sometimes, the request fails with 413 "Request Entity Too Large". This happens with and without me touching the config.

**Comment by pluja** [comment]
Are you using the docker-compose provided in the repo?

**Comment by North-West-Wind** [comment]
I ran the commands from https://whishper.net/guides/install/, so I'm assuming it is from the repo. I tried both quick install and manual install, and didn't change anything in docker-compose.

Some side note: The 3rd step in manual install has a `chown` command, which should actually be `chown -R`.

**Comment by pluja** [comment]
Does this happen with any file? Or is it a large file? If it is large, can you try with a smaller one?

About the sidenote: thanks, true, will change it later

**Comment by North-West-Wind** [comment]
This happens with every file. For larger ones (> 900MB), it ends with 502. For smaller ones (~ 70MB), it ends with 500.

If I change `nginx.conf`'s `client_max_body_size` to `10G`, larger ones end with 413, smaller ones are still 500.

**Comment by pluja** [comment]
How are you hosting whishper? Is it on localhost or is it behind a reverse proxy?

**Comment by North-West-Wind** [comment]
It is localhost. `docker-compose.yml` is not modified.

**Comment by pluja** [comment]
That's strange, do you see anything more in the logs? The `client_max_body_size` set to `0` in nginx means it's disabled.

**Comment by North-West-Wind** [comment]
I know `0` means it's disabled.

`whishper-backend` is spamming the following every 15 seconds since it starts:
```
DBG database/mongo.go:97 > Error getting transcriptions: connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.
```
When the web interface is opened, it also periodically sends this out about every minute:
```
ERR api/server.go:58 > Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
```

I did have a `fetch failed` error in the logs of `whishper-web` same as #10 when connecting to the web interface.
```
/api/transcriptions
TypeError: fetch failed
    at fetch (file:///app/shims.js:20346:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///app/server/index.js:3998:14)
    at async respond (file:///app/server/index.js:3823:22)
    at async fetch (file:///app/server/index.js:3633:26)
    at async Object.fetch (file:///app/server/index.js:3573:12)
    at async file:///app/server/index.js:1996:20
    at async load (file:///app/server/chunks/0-9ff9db82.js:9:20)
    at async load_data (file:///app/server/index.js:1978:18)
    at async file:///app/server/index.js:3307:18 {
  cause: [Error: 988BD1F2EA7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

There are nothing else significant in the other containers.

**Comment by pluja** [comment]
> I know 0 means it's disabled.

I was just clarifying to discard that nginx was blocking large files.

> whishper-backend is spamming the following every 15 seconds since it starts

The `mongodb` credentials are left as `MONGO_INITDB_ROOT_USERNAME: root` and `MONGO_INITDB_ROOT_PASSWORD: example` right? Just to make sure.

**Comment by North-West-Wind** [comment]
> The mongodb credentials are left as MONGO_INITDB_ROOT_USERNAME: root and MONGO_INITDB_ROOT_PASSWORD: example right? Just to make sure.

I actually changed it to test it earlier, my bad. But now I have changed it back and removed the `db_data` directory and the 15-second error is gone.

All the other things mentioned still exist though.

**Comment by pluja** [comment]
Hi, could you check again with the latest version? I have raised the backend max-body-size
