### ISSUE TITLE
ERR_SSL_WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by grigio** [pluja/whishper#41]
With the latest update it seems some API requires HTTPS SSL

```
ux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.32.1 - - [30/Oct/2023:17:54:49 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
whishper-web         | Listening on 0.0.0.0:3000
whishper-web         | TypeError: fetch failed
whishper-web         |     at fetch (file:///app/shims.js:20346:13)
whishper-web         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
whishper-web         |     at async resolve (file:///app/server/index.js:3661:14)
whishper-web         |     at async respond (file:///app/server/index.js:3479:22)
whishper-web         |     at async fetch (file:///app/server/index.js:3289:26)
whishper-web         |     at async Object.fetch (file:///app/server/index.js:3229:12)
whishper-web         |     at async file:///app/server/index.js:1341:20
whishper-web         |     at async load (file:///app/server/chunks/0-3c61a3ef.js:8:20)
whishper-web         |     at async load_data (file:///app/server/index.js:1323:18)
whishper-web         |     at async file:///app/server/index.js:2660:18 {
whishper-web         |   cause: [Error: B8894C42D67F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
whishper-web         |   ] {
whishper-web         |     library: 'SSL routines',
whishper-web         |     reason: 'wrong version number',
whishper-web         |     code: 'ERR_SSL_WRONG_VERSION_NUMBER'
whishper-web         |   }
whishper-web         | }
whishper-web         | TypeError: fetch failed
whishper-web         |     at fetch (file:///app/shims.js:20346:13)
whishper-web         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
whishper-web         |     at async resolve (file:///app/server/index.js:3636:16)
whishper-web         |     at async respond (file:///app/server/index.js:3479:22)
whishper-web         |     at async fetch (file:///app/server/index.js:3289:26)
whishper-web         |     at async Object.fetch (file:///app/server/index.js:3229:12)
whishper-web         |     at async file:///app/server/index.js:1341:20
whishper-web         |     at async load (file:///app/server/chunks/0-3c61a3ef.js:8:20)
whishper-web         |     at async load_data (file:///app/server/index.js:1323:18)
whishper-web         |     at async respond_with_error (file:///app/server/index.js:2291:20) {
whishper-web         |   cause: [Error: B8894C42D67F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
whishper-web         |   ] {
whishper-web         |     library: 'SSL routines',
whishper-web         |     reason: 'wrong version number',
whishper-web         |     code: 'ERR_SSL_WRONG_VERSION_NUMBER'
whishper-web         |   }
whishper-web         | }

```

**Comment by pluja** [comment]
Hello! A little while back, I put together some issue templates to streamline the bug reporting process. It's way easier if these templates are filled out from the get-go, saving me from having to ask for the same details with each new report. I'll be closing this issue, so I’d really appreciate it if you could open a new one and fill out the provided template. Thanks!
