### ISSUE TITLE
[BUG] Transcription problem

### ISSUE THREAD

**Issue by mosaad-apt** [pluja/whishper#61]
## **Description**
Try to use the UI but it doesn't work

### **To Reproduce**
I installed with the "easy" version and the manual but both time i have the same result.
I click on new transcription but it doesnt' work.

### Environment
- OS: [Ubuntu 22.04]
- Browser: [Firefox]
- Hosting: [Local]

### Docker Compose Logs

> Run the following command in the project folder, force the error, and paste the logs below: `docker compose logs -f --tail 50`

```
PASTE LOGS HERE
```
whishper                | 2023-12-01 17:05:31,047 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2023-12-01 17:05:31,048 INFO supervisord started with pid 1
whishper                | 2023-12-01 17:05:32,052 INFO spawned: 'backend' with pid 7
whishper                | 2023-12-01 17:05:32,056 INFO spawned: 'frontend' with pid 8
whishper                | 2023-12-01 17:05:32,061 INFO spawned: 'nginx' with pid 9
whishper                | 2023-12-01 17:05:32,064 INFO spawned: 'transcription' with pid 10
whishper                | 2023-12-01 17:05:33,249 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-01 17:05:33,249 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-01 17:05:33,249 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-01 17:05:33,249 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
documents-mongo-1       | {"t":{"$date":"2023-12-01T17:05:30.580Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2023-12-01T17-05-30"}}
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Downloading English → French (1.9) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → English (1.0) ...
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
### Docker Compose File

```yaml
PASTE YOUR DOCKER-COMPOSE.YML FILE HERE
```

**Comment by ADSFAaron** [comment]
## **Description**
I got the similar problem in my PC
Webpage shows UI, but transcription not work

### **To Reproduce**
Steps to reproduce the behavior:
Follow with [Manual Install](https://whishper.net/guides/install/#manual-install)
1. copy and paste:
```bash
curl -o docker-compose.yml https://raw.githubusercontent.com/pluja/whishper/main/docker-compose.yml && \
 curl -o .env https://raw.githubusercontent.com/pluja/whishper/main/example.env && \
 curl -o nginx.conf https://raw.githubusercontent.com/pluja/whishper/main/nginx.conf
```
2.  mkdir folder and permission
```bash
mkdir -p ./whishper_data/libretranslate/{data,cache} && \
chown -R 1032:1032 whishper_data/libretranslate
```

after command, permissions shows below

```bash
lab@lab-4080:~/whishper$ cd whishper_data/
lab@lab-4080:~/whishper/whishper_data$ ll
total 24
drwxrwxr-x 6  lab              lab 4096 十二  4 12:56 ./
drwxrwxr-x 3  lab              lab 4096 十二  4 12:55 ../
drwxr-xr-x 6 systemd-coredump root  4096 十二  4 15:00 db_data/
drwxrwxr-x 4             1032  1032 4096 十二  4 12:55 libretranslate/
drwxr-xr-x 2 root             root  4096 十二  4 12:56 logs/
drwxr-xr-x 2 root             root  4096 十二  4 12:56 uploads/
```

3. `docker compose up`

### **Expected behavior**
Start transcript and show the result

### Environment
- OS: Ubuntu 20.04.6 LTS x86_64
- Browser: Chrome 119.0.6045.200 
- Version: v3.1.0 - large-v3 support
- Hosting: Local

## Logs and Configuration
When enter devtools in browser -> Console Page, it show the error below

```
127.0.0.1:8082/api/transcriptions:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
app.2d54f27f.js:1 TypeError: Failed to fetch
    at window.fetch (start.ff3c76ab.js:1:1402)
    at st (start.ff3c76ab.js:1:1693)
    at fetch (start.ff3c76ab.js:1:10380)
    at g (0.51fc1021.js:1:298)
    at ue (start.ff3c76ab.js:1:10476)
    at async Promise.all (:8082/index 0)
    at async Object._hydrate (start.ff3c76ab.js:1:22173)
    at async Module.Ot (start.ff3c76ab.js:3:1669)
handleError @ app.2d54f27f.js:1
127.0.0.1:8082/api/transcriptions:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
start.ff3c76ab.js:1 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (start.ff3c76ab.js:1:1402)
    at st (start.ff3c76ab.js:1:1693)
    at fetch (start.ff3c76ab.js:1:10380)
    at g (0.51fc1021.js:1:298)
    at ue (start.ff3c76ab.js:1:10476)
    at async ie (start.ff3c76ab.js:1:13479)
    at async Object._hydrate (start.ff3c76ab.js:1:22457)
    at async Module.Ot (start.ff3c76ab.js:3:1669)
192.168.0.111/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

```

### Docker Compose Logs

```
whishper                | 2023-12-04 04:22:41,766 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2023-12-04 04:22:41,766 INFO supervisord started with pid 1
whishper                | 2023-12-04 04:22:42,770 INFO spawned: 'backend' with pid 7
whishper                | 2023-12-04 04:22:42,772 INFO spawned: 'frontend' with pid 8
whishper                | 2023-12-04 04:22:42,774 INFO spawned: 'nginx' with pid 9
whishper                | 2023-12-04 04:22:42,775 INFO spawned: 'transcription' with pid 10
whishper                | 2023-12-04 04:22:43,815 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:22:43,815 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:22:43,815 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:22:43,815 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:54:59,832 WARN received SIGTERM indicating exit request
whishper                | 2023-12-04 04:54:59,833 INFO waiting for backend, frontend, nginx, transcription to die
whishper                | 2023-12-04 04:55:00,184 INFO stopped: transcription (exit status 0)
whishper                | 2023-12-04 04:55:00,184 INFO stopped: nginx (exit status 0)
whishper                | 2023-12-04 04:55:00,186 INFO stopped: frontend (terminated by SIGTERM)
whishper                | 2023-12-04 04:55:00,187 INFO stopped: backend (terminated by SIGTERM)
whishper                | 2023-12-04 04:56:07,884 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2023-12-04 04:56:07,885 INFO supervisord started with pid 1
whishper                | 2023-12-04 04:56:08,888 INFO spawned: 'backend' with pid 6
whishper                | 2023-12-04 04:56:08,891 INFO spawned: 'frontend' with pid 7
whishper                | 2023-12-04 04:56:08,893 INFO spawned: 'nginx' with pid 8
whishper                | 2023-12-04 04:56:08,895 INFO spawned: 'transcription' with pid 9
whishper                | 2023-12-04 04:56:09,936 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:56:09,936 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:56:09,936 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 04:56:09,936 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 06:27:02,025 WARN received SIGTERM indicating exit request
whishper                | 2023-12-04 06:27:02,026 INFO waiting for backend, frontend, nginx, transcription to die
whishper                | 2023-12-04 06:27:02,367 INFO stopped: transcription (exit status 0)
whishper                | 2023-12-04 06:27:02,368 INFO stopped: nginx (exit status 0)
whishper                | 2023-12-04 06:27:02,370 INFO stopped: frontend (terminated by SIGTERM)
whishper                | 2023-12-04 06:27:02,371 INFO stopped: backend (terminated by SIGTERM)
whishper                | 2023-12-04 06:34:05,393 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2023-12-04 06:34:05,394 INFO supervisord started with pid 1
whishper                | 2023-12-04 06:34:06,397 INFO spawned: 'backend' with pid 7
whishper                | 2023-12-04 06:34:06,399 INFO spawned: 'frontend' with pid 8
whishper                | 2023-12-04 06:34:06,402 INFO spawned: 'nginx' with pid 9
whishper                | 2023-12-04 06:34:06,402 INFO spawned: 'transcription' with pid 10
whishper                | 2023-12-04 06:34:07,441 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 06:34:07,441 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 06:34:07,442 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-04 06:34:07,442 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Downloading English → French (1.9) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → English (1.0) ...
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.702+00:00"},"s":"I",  "c":"CONTROL",  "id":4784903, "ctx":"SignalHandler","msg":"Shutting down the LogicalSessionCache"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: going to close listening sockets"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"NETWORK",  "id":23017,   "ctx":"listener","msg":"removing socket file","attr":{"path":"/tmp/mongodb-27017.sock"}}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"SignalHandler","msg":"Shutting down the global connection pool"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":4784906, "ctx":"SignalHandler","msg":"Shutting down the FlowControlTicketholder"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":4784908, "ctx":"SignalHandler","msg":"Shutting down the PeriodicThreadToAbortExpiredTransactions"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"REPL",     "id":4784909, "ctx":"SignalHandler","msg":"Shutting down the ReplicationCoordinator"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"SHARDING", "id":4784910, "ctx":"SignalHandler","msg":"Shutting down the ShardingInitializationMongoD"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"REPL",     "id":4784911, "ctx":"SignalHandler","msg":"Enqueuing the ReplicationStateTransitionLock for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"-",        "id":4784912, "ctx":"SignalHandler","msg":"Killing all operations for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"-",        "id":4695300, "ctx":"SignalHandler","msg":"Interrupted all currently running operations","attr":{"opsKilled":3}}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"TENANT_M", "id":5093807, "ctx":"SignalHandler","msg":"Shutting down all TenantMigrationAccessBlockers on global shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"TenantMigrationBlockerNet","msg":"Killing all outstanding egress activity."}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"ASIO",     "id":6529201, "ctx":"SignalHandler","msg":"Network interface redundant shutdown","attr":{"state":"Stopped"}}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"SignalHandler","msg":"Killing all outstanding egress activity."}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"COMMAND",  "id":4784913, "ctx":"SignalHandler","msg":"Shutting down all open transactions"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"REPL",     "id":4784914, "ctx":"SignalHandler","msg":"Acquiring the ReplicationStateTransitionLock for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"INDEX",    "id":4784915, "ctx":"SignalHandler","msg":"Shutting down the IndexBuildsCoordinator"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"MigrationUtil-TaskExecutor","msg":"Killing all outstanding egress activity."}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"COMMAND",  "id":4784923, "ctx":"SignalHandler","msg":"Shutting down the ServiceEntryPoint"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":4784928, "ctx":"SignalHandler","msg":"Shutting down the TTL monitor"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"INDEX",    "id":3684100, "ctx":"SignalHandler","msg":"Shutting down TTL collection monitor thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"INDEX",    "id":3684101, "ctx":"SignalHandler","msg":"Finished shutting down TTL collection monitor thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":6278511, "ctx":"SignalHandler","msg":"Shutting down the Change Stream Expired Pre-images Remover"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"CONTROL",  "id":4784930, "ctx":"SignalHandler","msg":"Shutting down the storage engine"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22320,   "ctx":"SignalHandler","msg":"Shutting down journal flusher thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22321,   "ctx":"SignalHandler","msg":"Finished shutting down journal flusher thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22322,   "ctx":"SignalHandler","msg":"Shutting down checkpoint thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22323,   "ctx":"SignalHandler","msg":"Finished shutting down checkpoint thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22261,   "ctx":"SignalHandler","msg":"Timestamp monitor shutting down"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":20282,   "ctx":"SignalHandler","msg":"Deregistering all the collections"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22317,   "ctx":"SignalHandler","msg":"WiredTigerKVEngine shutting down"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22318,   "ctx":"SignalHandler","msg":"Shutting down session sweeper thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":22319,   "ctx":"SignalHandler","msg":"Finished shutting down session sweeper thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.703+00:00"},"s":"I",  "c":"STORAGE",  "id":4795902, "ctx":"SignalHandler","msg":"Closing WiredTiger","attr":{"closeConfig":"leak_memory=true,use_timestamp=false,"}}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.713+00:00"},"s":"I",  "c":"STORAGE",  "id":4795901, "ctx":"SignalHandler","msg":"WiredTiger closed","attr":{"durationMillis":10}}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.713+00:00"},"s":"I",  "c":"STORAGE",  "id":22279,   "ctx":"SignalHandler","msg":"shutdown: removing fs lock..."}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.713+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.713+00:00"},"s":"I",  "c":"FTDC",     "id":20626,   "ctx":"SignalHandler","msg":"Shutting down full-time diagnostic data capture"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.715+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
whishper-mongo-1        | {"t":{"$date":"2023-12-04T04:56:09.715+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}
whishper-mongo-1        | 
whishper-mongo-1        | MongoDB init process complete; ready for start up.
whishper-mongo-1        | 
whishper-mongo-1        | {"t":{"$date":"2023-12-04T06:34:05.060Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2023-12-04T06-34-05"}}
```

### Docker Compose File

```yaml
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest-cuda
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    user: root
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,fr,es}
      LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest-gpu}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: gpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```
